name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - uses: actions/setup-python@v2
      with:
        node-version: 16
        python-version: '3.8'
    - name: Install Python 3.8 and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common python3-distutils
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python3.8 python3.8-distutils
        python -m venv venv
        source venv/bin/activate
        python -m pip install -r requirements.txt
    - name: Install latest version of pip
      run: python3.8 -m pip install --upgrade pip
    - name: Install Flask
      run: python3.8 -m pip install flask
    - name: Install dependencies
      run: npm ci
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
